// <auto-generated />
using System;
using CloudStore.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CloudStore.Infrastructure.Migrations
{
    [DbContext(typeof(CloudStoreDbContext))]
    [Migration("20260627195141_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CloudStore.Infrastructure.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 6, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "High-performance laptop for developers",
                            ImageUrl = "https://placehold.co/400x300?text=Laptop",
                            Name = "Laptop",
                            Price = 1299.99m,
                            UpdatedAt = new DateTime(2026, 6, 27, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 6, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Cherry MX switches, RGB backlit",
                            ImageUrl = "https://placehold.co/400x300?text=Keyboard",
                            Name = "Mechanical Keyboard",
                            Price = 149.99m,
                            UpdatedAt = new DateTime(2026, 6, 27, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 6, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Dell UltraSharp 27-inch 4K monitor",
                            ImageUrl = "https://placehold.co/400x300?text=Monitor",
                            Name = "4K Monitor",
                            Price = 599.99m,
                            UpdatedAt = new DateTime(2026, 6, 27, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
